### PR TITLE
add olsson17

### LINKED ISSUE #13: add Jack Olsson
#### How to get started

1) star this repository (top right) so that we can help you get more visibility over your open source contributions
2) follow the [README.md instructions](https://github.com/the-fast-tracked-programmer/first-contributions) to learn how to make your first contribution to an open source project

#### If you get stuck and need some guidance or support

Jump into our discord channel [#first-contributions](https://discord.com/invite/2QaYgquy6R) and request some help from an experienced mentor

### PR DESCRIPTION
**Pull request by olsson17**
closes #13

### CODE REVIEW

**Review by Subskii — CHANGES_REQUESTED** [review]
Almost there @olsson17 

Just need to update the pull request description with `closes #13` so that the issue will be closed automatically when we merge this thing :)

Once you've done that just re-request a review and we'll give the :+1:

**Comment by olsson17** [comment]
closes #13

**Comment by Subskii** [comment]
Doesn't seem to associate the pull request with the issue if it's linked in the comment.

Try this instead:

jack

**Comment by Subskii** [comment]
Bingo! :rocket: 

Great stuff @olsson17 :tada: :tada:

**Pull request merged**
