### PR TITLE
add srijani07

### PR DESCRIPTION
**Pull request by srijani07**
closes #35

### CODE REVIEW

**Comment by Subskii** [comment]
Hey @srijani07 :smiley: 

Looks like you just need to remove the `<>` in the pull request description number (e.g. `closes #24`), so that pull request can be linked to the issue when I merge.

Could you update that, and then request a review from the mentors? Thanks!

**Review by Subskii — CHANGES_REQUESTED** [review]
That's more like it.

Final issue: file `srijani07.md` actually goes in the `first-contributions/` folder (within the repo) e.g. `first-contributions/srijani07.md`

Once that's done I can merge :smile:

**Comment by srijani07** [comment]
Hi, Adam. Firstly, thanks a ton for all the help. I couldn't get the linking issue to a PR right on the first try. Have created a new pull request.

**Comment by Subskii** [comment]
Awesome have merged the other PR. Will close this one. Killing it :rocket: !

**Pull request closed without merging**
