### PR TITLE
add rajeshkumarrs

### LINKED ISSUE #22: add Rajesh Kumarrs

### PR DESCRIPTION
**Pull request by rajeshkumarrs**
closes #22

### CODE REVIEW

**Review by Subskii — CHANGES_REQUESTED** [review]
Hey @rajeshkumarrs just need to move this file into the `first-contributions/` folder in the repository :)

Can request another review once you're done!

**Comment by rajeshkumarrs** [comment]
Thanks :). I have moved the rajeshkumarrs.md file into first-contributions folder and committed the same.

**Comment by Subskii** [comment]
Looking good @rajeshkumarrs :ok_hand: 

Last step is to re-request a review, so we can get your first pull request merged! :smile:

**Comment by Subskii** [comment]
Great stuff @rajeshkumarrs! 😃

**Pull request merged**
