### PR TITLE
add jkiyak

### LINKED ISSUE #74: add John Kiyak
#### How to get started

1) star this repository (top right) so that we can help you get more visibility over your open source contributions
2) follow the [README.md instructions](https://github.com/the-fast-tracked-programmer/first-contributions) to learn how to make your first contribution to an open source project

#### If you get stuck and need some guidance or support

Jump into our discord channel [#first-contributions](https://discord.com/invite/2QaYgquy6R) and request some help from an experienced mentor

### PR DESCRIPTION
**Pull request by jkiyak**
closes #74

### CODE REVIEW

**Review by Subskii — CHANGES_REQUESTED** [review]
Awesome work so far @jkiyak

3 things left to do:

1) move `jkiyak.md` into `first-contributions/jkiyak.md`
2) update the pull request description with `closes #74` so that your pull request is linked to the original issue
3) Re-request changes so we can take another look and merge!

**Comment by jkiyak** [comment]
closes #74

**Comment by Subskii** [comment]
> closes #74

Almost there. Unfortunately GitHub requires us to update the pull request description for it to work properly.

How to do that here:

https://github.com/the-fast-tracked-programmer/first-contributions/pull/73#issuecomment-913349659

**Review by Subskii — APPROVED** [review]
Great work John! :tada: :tada:

**Pull request merged**
