### PR TITLE
add Tangjas20

### LINKED ISSUE #15: add Jason Tang

### PR DESCRIPTION
**Pull request by Tangjas20**
closes #15

### CODE REVIEW

**Review by Subskii — CHANGES_REQUESTED** [review]
Just need to update the pull request description so it's properly linked to the issue @Tangjas20  e.g. closes #15

**Comment by Tangjas20** [comment]
Just edited the pull request description. Will I need to do anything else to confirm the changes?

**Comment by Subskii** [comment]
Perfect @Tangjas20

Just need to re-request a review and I can get this one merged 😃

**Comment by Subskii** [comment]
Awesome work @Tangjas20 🎉 🎉

**Pull request merged**
